### ISSUE TITLE
Version 50 Moons

### ISSUE THREAD

**Issue by Drewzyu** [BananaPuncher714/LethalQuantities#107]
Hi, I assume this question has been asked before, but is there any chance of this mod receiving support for the new moons in Version 50? 
And if the mod already has support for these moons, how do I edit them? I saw that modded moons were possible to edit in the editor, so I am wondering how to change the in-game ones as well. Thank you for your time!

**Comment by BananaPuncher714** [comment]
After booting up the game and loading into the ship the presets.json should be populated with the new moon information. It should have all the relevant data when you edit in the web ui.
