### ISSUE TITLE
Was the mod still maintained?

### ISSUE THREAD

**Issue by Xeraccoon** [BananaPuncher714/LethalQuantities#109]
Hello, I am posting this issue, just to know if the mod is maintained before starting to make lots of modifications, thank you in advance, you can close this issue after answer.

**Comment by BananaPuncher714** [comment]
Hi, I have a todo list with stuff that I kind of want to implement, but I don't have the time. If you'd like to make a fork or stuff then feel free. 😃

**Comment by Xeraccoon** [comment]
if "If you'd like to make a fork" is an expression not being an English speaker I can't understand ^^ in French it literally means nothing ^^ but if the question are I am a developer ? the answer is unfortunately no, in which case I would have contributed with pleasure.
My concern was that the plugin would be abandoned and become incompatible with future official updates.
thank you for the answer in any case it is reassuring to know that you are not far from your plugin.
Thanks for this great plugin in any case which is, in my opinion, one of the most essential plugins.
