### ISSUE TITLE
Confused how to set enemy/etc spawns

### ISSUE THREAD

**Issue by mitztastic** [BananaPuncher714/LethalQuantities#11]
For example, I try to modify Vow and set all the enemies to Rarity=0, MaxEnemyCount=0, except the one spawn that I want to appear--which I gave a high rarity value (does that make it more or less common relative to others)... Still all kinds of monsters appear but the one I intended, any tips?

**Comment by BananaPuncher714** [comment]
Are you modifying the `LethalQuantities/Moons/Vow/Enemies.cfg`, and did you set the config to enabled in the `General` section? And, do you have any other mods installed?

**Comment by mitztastic** [comment]
Hilariously I forgot to reinstall it after troubleshooting, I was only modifying the remaining config files apparently.
For now I think it's probably working. Might check later with further mods and if I run into issues I'll probably post here.
Thanks for this useful tool though! Cheers!

**Comment by BananaPuncher714** [comment]
Ok great! Definitely re-open this if you run into any more issues, thanks!
