### ISSUE TITLE
Can't spawn more than 502 items

### ISSUE THREAD

**Issue by mike282** [BananaPuncher714/LethalQuantities#12]
Hello! First of all, thanks for your mod! Everything seems to work apart from one thing: i wanted to see, just for fun, how many items my computer could take without exploding, but noticed that if i set to spawn a minimum of 1000 items, it spawns only 500. Could it be that there is a hard limit that can't be surpassed? 

P.S I tried again now, just to confirm, and with a minimum of 1000 items it spawned 428

**Comment by BananaPuncher714** [comment]
There is no hard coded limit, but there are only a limited amount of spawning locations for scrap, which differs based on the generation of each map. It may be that there are simply no more places to put a piece of scrap, at which point the game stops trying to spawn any more items.

**Comment by mike282** [comment]
Perhaps there will be a method to add more spawn points in the future?

**Comment by BananaPuncher714** [comment]
It would be difficult to change unless I were to rewrite the scrap spawning logic completely. You can use another mod to increase the map size to add more scrap spawn points, but I cannot increase that limit currently.

**Comment by mike282** [comment]
You're right, thanks a lot!!
