### ISSUE TITLE
how i use spawn amount curve on general? and why on the company cant spawn enemies when editing?

### ISSUE THREAD

**Issue by Mickael46999** [BananaPuncher714/LethalQuantities#13]

**Comment by BananaPuncher714** [comment]
The spawn amount curve is a unity animation curve which is described [here](https://lethal.miraheze.org/wiki/Mechanics). The amount of enemies that spawns depends on the time of day(X axis), and what the current Y value of the animation curve is at that time.

The X value or key of the animation curve ranges from 0 to 1, where 0 is when the day starts, and 1 is when the day ends. The Y value is the amount of enemies to spawn. For example, if you want it to always spawn 1 enemy, then you can use the animation curve `0:1, 1:1`. If you want it to only start spawning enemies after the middle of the day, you can use the curve `0:0, .5:0, 1:7`. The real amount spawned also depends on the spawn amount range, so it may not always be the same.

You can copy the default spawn amount curve and increase the Y value if you want more enemies to spawn.

**Comment by Mickael46999** [comment]
it doesnt save the values when i modify it

**Comment by BananaPuncher714** [comment]
Reopened in issue #15
