### ISSUE TITLE
bug enemies and outsite enemies 

### ISSUE THREAD

**Issue by Mickael46999** [BananaPuncher714/LethalQuantities#16]
dont work, just dont spawn nothing and sometimes it change it to the vanilla, if you put it false  or vanilla it just dont work nothing and no enemy spawn

**Comment by BananaPuncher714** [comment]
Are you sure you are not typing the curve incorrectly or forgetting a period?

**Comment by Mickael46999** [comment]
yes im sure

**Comment by Mickael46999** [comment]
i have
enemies 0:5, 3:4, 5:4, 7:61
outsite 3:3, 6:4, 8:4

**Comment by Mickael46999** [comment]
if i put 0.5 the game change it to 5

**Comment by BananaPuncher714** [comment]
If the config is not saving correctly, then provide the steps in ticket #15. As for the curve, **it only goes from 0 to 1**. So, any value such as 3:4 or 7:61 is not applied properly. If you do not think any enemies are spawning, then try the curve `0:100, 1:100`. You must also enable the config and increase the max power level to a high number, such as 100. If that does not work, then provide your entire config file, and state which moon it is for.

**Comment by Mickael46999** [comment]
it dont work, im using 0:10, 1:20

**Comment by BananaPuncher714** [comment]
State which mods you are using, and provide all your configuration files.

**Comment by Mickael46999** [comment]
![imagen_2023-12-26_235921971](https://github.com/BananaPuncher714/LethalQuantities/assets/154325292/1162b3d8-bca6-4ca7-a8ec-a6ce0401eb4b)

Daytime: 
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/154325292/a9f6225a-75bd-4bee-a165-25d8ae0c5cdc)

enemies 
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/154325292/93971014-bce2-49aa-b521-ee0ca77832ed)

outsite
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/154325292/2ee2a552-b49e-44c6-ad17-f639f92c51ba)

i tried with bigger values but just nothing appear. only if i use 0:1, 1:1

**Comment by Mickael46999** [comment]
im trying only with the mod and bipex, but nothing spawn

**Comment by BananaPuncher714** [comment]
Set the spawn amount curve to `0:100, 1:100`, and set the spawn amount range to `0`. If this does not work then there is nothing more I can do for you.

**Comment by Mickael46999** [comment]
Yeah that work, but other thing for me like another curves dont

**Comment by BananaPuncher714** [comment]
The curves do work. You did not read the spawn amount range description properly. The curves you use do not guarantee that an enemy will spawn. You need to adjust the curve yourself and determine which one is correct for you.

**Comment by Mickael46999** [comment]
can you explain me more the amount range

**Comment by Mickael46999** [comment]
im trying everything to make enemies and outsite enemies work, but its imposible they just dont work

**Comment by Mickael46999** [comment]
they curve when i use in outsite 0:-2, 0.4:6, 1:12 amountrange 10, powercount 100 dont work

**Comment by BananaPuncher714** [comment]
Closing this issue unless you can prove that there is a bug. I have not managed to reproduce any issues you have, or experienced any unexpected behaviors when editing the config properly. Your expectations are not clear, and I don't know what you want.
