### ISSUE TITLE
resseting values curve

### ISSUE THREAD

**Issue by Mickael46999** [BananaPuncher714/LethalQuantities#17]
i am using 0:0, 0,5:3 0,7:5, 1:3 and the game reset it to the default. i tried everything you tell me but it doesnt save it just put the default when you reset 2-5 times the game. like in daytime it works but it reset the values for no reason its strange

**Comment by BananaPuncher714** [comment]
Please do not open another issue when there is already one open(#15) for this exact problem. I have also stated many times that you must use periods, not commas to represent a decimal number.

**Comment by Mickael46999** [comment]
what is a period? im spanish sorry my english isnt good and sorry for open another
