### ISSUE TITLE
Question: Can you check if your mod works with weather?

### ISSUE THREAD

**Issue by FireGeneral** [BananaPuncher714/LethalQuantities#2]
I haven't checked this, but... After browsing through the config files, the "bunker spider" stood out for me. 
Its default "MaxEnemyCount = 1" but for numerous occasions, I've encountered more than 1 bunker spider on moons with weather conditions (presumably Eclipse). 
This made me wonder how does weather affect enemy spawn? MaxEnemyCount and such, and the fact wether your mod takes those into account. Thank you!

**Comment by BananaPuncher714** [comment]
Hi, eclipse weather affects the minimum number of enemies to spawn inside and outside, when a chance to spawn an enemy is available. This is why in daytime, enemies spawn even though they normally would not. However, the minimum number of enemies should not affect what types of enemies that spawn(based on their max count and other variables).

Since this mod doesn't change the spawn logic, only the numbers, weather shouldn't differ from the vanilla behavior. I'm not sure why there is more than one bunker spider spawning, but it could be another mod influencing the spawn rates or forcefully spawning spiders in. As a side note, all configs are disabled by default and do not affect gameplay in any way unless enabled.

**Comment by FireGeneral** [comment]
> Hi, eclipse weather affects the minimum number of enemies to spawn inside and outside, when a chance to spawn an enemy is available. This is why in daytime, enemies spawn even though they normally would not. However, the minimum number of enemies should not affect what types of enemies that spawn(based on their max count and other variables).
> 
> Since this mod doesn't change the spawn logic, only the numbers, weather shouldn't differ from the vanilla behavior. I'm not sure why there is more than one bunker spider spawning, but it could be another mod influencing the spawn rates or forcefully spawning spiders in. As a side note, all configs are disabled by default and do not affect gameplay in any way unless enabled.

I see, however, I've encountered the more than one spider spawning situations even when I was playing the game without any mods. Hence my surprise when I found out through your mod that spiders have a maximum number of 1 per map.

Btw, if you don't mind. Can you explain to me how the game treat "dead" monsters? Like how those affect the "MaxEnemyCount" and the "MaxPowerCount"? Thank you!

**Comment by BananaPuncher714** [comment]
Once an enemy is killed, it only decreases the power level and allows more enemies to spawn. However, it does not decrease the enemy count for that type, and should not allow more enemies of that type to spawn, if it has already hit the MaxEnemyCount. I don't know why there is more than one spider. 🤔

For the rarity, it is a misconception that it needs to be between 0 and 100. The rarity refers to a weight for that particular type. For example, if a spider has a rarity of 60, and a hoarding bug has a rarity of 40, then the spider has a 60/(60+40) = 60% chance to spawn. Likewise, if both the spider and hoarding bug have a rarity of 1, then both enemies have a 1/(1+1) = 50% chance to spawn.  Limiting the total rarity of all the enemies combined to 100 is just to make it convenient for calculating their spawn chances.

**Comment by FireGeneral** [comment]
> Once an enemy is killed, it only decreases the power level and allows more enemies to spawn. However, it does not decrease the enemy count for that type, and should not allow more enemies of that type to spawn, if it has already hit the MaxEnemyCount. I don't know why there is more than one spider. 🤔
> 
> For the rarity, it is a misconception that it needs to be between 0 and 100. The rarity refers to a weight for that particular type. For example, if a spider has a rarity of 60, and a hoarding bug has a rarity of 40, then the spider has a 60/(60+40) = 60% chance to spawn. Likewise, if both the spider and hoarding bug have a rarity of 1, then both enemies have a 1/(1+1) = 50% chance to spawn. Limiting the total rarity of all the enemies combined to 100 is just to make it convenient for calculating their spawn chances.

Understood! Thank you!

**Comment by BananaPuncher714** [comment]
This seems to be fixed/answered, so if any errors/bugs still persist, please open a new issue. Thanks!
