### ISSUE TITLE
[Question] Does a higher rarity mean the enemy is more or less likely to spawn?

### ISSUE THREAD

**Issue by elliott-w** [BananaPuncher714/LethalQuantities#20]
Seems like a dumb question but I'm getting confusing results in game.

**Comment by Simmmmms** [comment]
Higher rarity means that the enemy should spawn more often. The chance to spawn is Rarity of Monster / Sum of all monster rarities.

**Comment by elliott-w** [comment]
Okay thanks, very confusing because I would think higher rarity = spawns less xD

**Comment by BananaPuncher714** [comment]
It would technically make more sense to call it a "weight", but since it's called "rarity" in game, I didn't really want to go around making up new terminology that may or may not be what the original developer intended.

**Comment by elliott-w** [comment]
Maybe mention it in the comments of the config somewhere?

**Comment by BananaPuncher714** [comment]
Hmm, I can see how it may be hard to understand. It's in the README, but I'll add it to the config file description with a more concise explanation so it's less confusing in the future.
> The weight given to this enemy vs other enemies. If you do not want the enemy to spawn, set the rarity to 0.
