### ISSUE TITLE
Bug withthe mod SpectateEnemies

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#24]
The host can't spectate enemies anymore when using LethalQuantities while clients can.

**Comment by BananaPuncher714** [comment]
Ok thanks I'll take a look into this.

**Comment by TheRealMrKam** [comment]
Forgot to precise it's on v40, tested with all the versions of spectate (some spectate do not work with v40, 1.3.0 does)
