### ISSUE TITLE
NPC refusing to spawn

### ISSUE THREAD

**Issue by user7562** [BananaPuncher714/LethalQuantities#25]
after i modified the powerlevel of a moon and of a enemy they refuse to spawn inside the facility. help?

**Comment by Simmmmms** [comment]
Can you attach the file of the config for the moon you have modified.

**Comment by user7562** [comment]
of course, here

**Comment by user7562** [comment]
of course, here. same goes for every other moon

**Comment by Simmmmms** [comment]
It doesn't seem to have attached correctly. Could you just send the export code of your r2modman profile with the settings changed. You can get the code by going to settings and searching for Export profile as a code.

**Comment by user7562** [comment]
i have the mod manually installed, i dont have thunderstore sadly but i can send you the entire text of the config in a reply if thats ok.

**Comment by user7562** [comment]
i've zipped all 4 configs of a moon and sent it to you via email if you havent checked already btw

**Comment by Simmmmms** [comment]
I'm not sure which email you sent it it to, I do not see it anywhere. Try sending it to simms@aaaaahhhhhhh.com.

**Comment by Simmmmms** [comment]
Which mob are you trying to edit, and how are you confirming that they are not spawning. The configs you sent contained a lot of enemies with really low rarities, which may be making it seem as if they are not spawning.

**Comment by user7562** [comment]
i have made the following npcs spawn at day:
giant
spider
sandworm
bracken
spore lizard
dog
torso
baboon

for some reason it only spawns a spore lizard, and animals like birds and locusts dont spawn for some reason. same goes for enemies inside the facility, they just refuse to spawn at all.

**Comment by Simmmmms** [comment]
It seems that you removed the default spawn curves. This is probably whats causing the enemies not to spawn inside, I changed the spawn curve to default and mobs were spawning fine. Try re-adding the default spawn curves or making custom ones, but don't leave them blank.

**Comment by user7562** [comment]
while i was testing to see what was the problem i removed the spawn curves, thought that would help but it didnt. i'm not sure if it works or not now, ive tested it ingame and monsters do spawn. i will be testing and thanks for the help.

**Comment by user7562** [comment]
Another problem that im having is that for example, if i set a scrap value to 10-20 sometimes the value is above the maximum. is this even fixable?

**Comment by user7562** [comment]
the mod appears to be still broken, i have set the manticoil rarity to 100 on certain moons and they dont even spawn. what is happening?

**Comment by Simmmmms** [comment]
Which config are editing, and where are trying to have them spawn?

**Comment by user7562** [comment]
at first, i tried making them spawn inside the facility and that might broke the spawning, because there is no air nodes inside the facility so i had to remove them from spawning inside. now they only spawn outside. as for the rarity, the birds and the friendly locusts are the most common npc that spawn outside. as for the inside, the most common are: spider, hoarder bug, snare flea. and yet they dont spawn. npcs dont even spawn upon landing on the map.

**Comment by BananaPuncher714** [comment]
What are you attempting to do?

First of all, you **must** set the spawn amount curve. Secondly, enemy spawning is not immediate, so even if you set the spawn amount curve extremely high, you will have to wait a minute or so until enemies spawn.

The daytime enemy config is for passive enemies, like manticoils and locusts. If you want to modify enemies that spawn outside, then you should edit the OutsideEnemies.cfg file. The spawning of enemies outside does not affect enemies inside, and vice versa.

**If you are not sure if an enemy is spawning, then increase the rarity to 9999, and increase the spawn amount curve to 100, and set the spawn amount range to 0.** This will ensure the enemies are almost guaranteed to spawn, and prove the config is working. If you aren't sure how the spawn amount curve works, then look at the default value as an example.

I don't know why manticoils would or would not spawn inside, but this mod can't fix that if it's a manticoil specific issue.

I can guarantee that the enemy spawn rates are modified properly, but other mods can and will change the spawn rates if they want to.

**Comment by user7562** [comment]
I am attempting to increase the max monster cap of enemies and make inside enemies spawn outside as well, i have removed the spawn curve as i was testing why isnt anything spawning. i have waited an entire day ingame to see if something spawns, absolutely nothing. Isn't DayTimeMonsters.cfg suppose to control what enemies spawn at day and OutsideMonsters only for night time? I have no other mods that modify or change the spawning behavior of npcs.

**Comment by BananaPuncher714** [comment]
The spawn amount curve is necessary. If you remove it, then it defaults to 0. Like I have stated previously, set the spawn curve to `0:100,1:100` if you want enemies to spawn. You can lower it to an amount you are comfortable with later on.

No, daytime enemies is for passive enemies like manticoils, and outside enemies is for hostile enemies like eyeless dogs. The only reason why outside enemies spawn outside later in the day is because the spawn amount curve is designed that way. You can change the spawn amount curve so they can spawn at all times.

**Comment by user7562** [comment]
interesting, does the spore lizard count as a passive enemy?

**Comment by BananaPuncher714** [comment]
I called it passive enemies, and hostile enemies, but really there is no difference except for what was originally in the daytime and outside enemy configs. You can spawn any enemy in the daytime enemies list, but I can't guarantee that there isn't some other behavior that might happen(like despawning later). If you want to spawn enemies, you should use OutsideEnemies.cfg. The daytime enemies config is there just for completeness.
