### ISSUE TITLE
Weird animation curve problem

### ISSUE THREAD

**Issue by Riameime** [BananaPuncher714/LethalQuantities#26]
Tested with only BepInExPack+LethalQuantities installed.
018ce396-f202-f3a7-50ae-832045bbf4cb

When I first load the game it creates config files with default animation curves like (Experimentation/Enemies):

SpawnAmountCurve = 0,001541138:-3, 0,4575331:4,796203, 0,7593884:4,973001, 1:15

Which is weird I guess cause it should use period, right?

On second load, existing configs, no changes made by me, console gives error for every animation curve:

[Warning:   BepInEx] Config value of setting "General.SpawnAmountCurve" could not be parsed and will be ignored. Reason: Index was outside the bounds of the array.; Value: 0,001541138:-3, 0,4575331:4,796203, 0,7593884:4,973001, 1:15
[Warning:   BepInEx] Config value of setting "EnemyTypes.BaboonHawk.SpawnFalloffCurve" could not be parsed and will be ignored. Reason: Index was outside the bounds of the array.; Value: 0:1, 0,1022146:1,954167, 0,2093059:2,709228, 0,3081509:1,460442, 0,5155956:0,7506728, 1:0,2186031
[Warning:   BepInEx] Config value of setting "EnemyTypes.Blob.SpawnChanceCurve" could not be parsed and will be ignored. Reason: Index was outside the bounds of the array.; Value: 0:1, 0,5870568:0,9988297, 1:0,9582062
...
etc

If I try to change values using periods:

[Warning:   BepInEx] Config value of setting "General.SpawnAmountCurve" could not be parsed and will be ignored. Reason: Input string was not in a correct format.; Value: 0:0, 0.5:2.5, 1:15

Need help, what am I doing wrong?

**Comment by BananaPuncher714** [comment]
Yes, it should 100% use a period for decimals, and use a comma for separators. After further research, it appears that C# uses commas instead of dots depending on the culture/region your operating system is set to. I'll try to have this fixed, thanks!
