### ISSUE TITLE
 How does SpawnChanceCurve works ?

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#27]
Can you help me understand how SpawnChanceCurve works  ?
for exemple : SpawnChanceCurve = 0:1, 0.1073834:1, 0.1368088:0, 1:0
I have no idea what this numbers stand for.
And why in the exemple there is 3 commas and sometimes there is only one like this : SpawnChanceCurve = 0:1, 1:1  ?

**Comment by Simmmmms** [comment]
I drew up an example of a spawn chance curve of 0:0, 0.5, 1:1. It basically just means that for the first half of the day (0 to .5) there is an extremely low chance for that monster to spawn, then after the halfway point the chance begins to climb until at the very end of the day it has a normal spawn chance. 
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/3964283/503dab58-0fe2-422d-b170-d1c834fce4f5)

You can add as many key:value pairs as you like to change the shape of the graph. Take a look at [this](https://docs.unity3d.com/Manual/animeditor-AnimationCurves.html) page for more information.

**Comment by TheRealMrKam** [comment]
Ok ! i think i understand better now, thank you good sir !
