### ISSUE TITLE
Enemies not spawning when strings in global config file are left default or blank

### ISSUE THREAD

**Issue by Calavid** [BananaPuncher714/LethalQuantities#29]
It appears that the game is reading the "DEFAULT" and "[blank]" strings in the global config files as "0" instead of whatever the base game default is, preventing anything from spawning. Filling each of these strings out manually appears to solve the problem so the mod seems to be working at least, but the way the file generates currently causes nothing to spawn in the interior area. 

Have not tested with the global scrap file or outside enemy files.

**Comment by BananaPuncher714** [comment]
Which options are you trying to set? A blank value should always use the original game value, but I may have messed up an option somewhere.

**Comment by Calavid** [comment]
Ive set some power level and spawn cap options for a few enemy types, and made it so some take '9999' seconds to open doors, but everything else is blank.

I tried a fresh mod profile with just LQ, using the default configs that it generates for itself, and everything seems to work fine. but as soon as i specify some of the values, everything stops spawning.

Here are the values i am altering for my SoloPlay rebalance modpack;
Blob.PowerLevel = 2
Centipede.DoorSpeedMultiplier = 9999
Crawler.MaxEnemyCount = 3
DressGirl.MaxEnemyCount = 0
DressGirl.PowerLevel = 4
DressGirl.SpawnChanceCurve = 0:1, 0:1
Masked.MaxEnemyCount = 5
Masked.PowerLevel = 2
Nutcracker.MaxEnemyCOunt = 6
Puffer.MaxEnemyCount = 3
SpringMan.MaxEnemyCount = 3
SpringMan.PowerLevel = 3
Rarity.DressGirl = 0

Everything else is blank.

**Comment by BananaPuncher714** [comment]
Ok thanks I'll take a look. I'm assuming that these values are for a moon's Enemies.cfg, and the global Enemies.cfg is also enabled, but blank?

**Comment by Calavid** [comment]
No, these values are for the global enemies config, which is the only one generated and enabled.

**Comment by BananaPuncher714** [comment]
Hmm, ok. I'll do some testing my end and get back to you.

**Comment by Calavid** [comment]
Im doing some more testing with various combinations of those values to see which, if any of them, could be the cause

**Comment by BananaPuncher714** [comment]
Ok, it seems like I was not using the correct list(an empty one) when searching for the default rarity, which caused the "default" rarity of all enemies to be 0. I'll have this fixed soon, hopefully, but for now if you enable the moon config without modifications, it _should_ spawn enemies like normal.

**Comment by Calavid** [comment]
Pogging. Tanks for looking into it!
