### ISSUE TITLE
Question and possible Bugs: How do I tweak the "SpawnAmountCurve"?

### ISSUE THREAD

**Issue by FireGeneral** [BananaPuncher714/LethalQuantities#3]
So... I understand that the AnimationCurves dependent on time are always from 0 to 1. 
I understand that the AnimationCurves are not a linear progression from one frame to another, and they're modelled by Unity's AnimationCurve.

What I don't understand is how do we change it so it could work in our game?
Let me explain, here I took March as an example.
I changed its SpawnAmountCurve from its original "4.410501" to "1.410501" and observed its result.
![Mod Pic 001](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/6f932c92-78ce-4caa-adbd-3881a58c213e)

Inside the game, I used another mod called "ScanForEnemies" to observe the enemy spawns. However, I immediately notice the game listed all of its monsters despite it didn't actually spawn any of them. (I didn't check thoroughly)
![Mod Pic 002](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/80f1a5fa-9501-4ac7-8055-a2751aae90d6)

Also, since I've tweaked all monsters' power levels, the value just doesn't make sense. (The total enemy power level will not exceed but can equal the maximum power count.)
I made is so that March had a "MaxPowerCount = 7" for inside enemies, and a single "FlowerMan" had 6 Powerlevel, making it odd for the mod to violate its own spawn rule. (I'll skip other monsters' power levels, knowing their total power level already exceeded the maximum power count I set for the moon)

Then, when I walked outside the ship, I found a floating bunker spider twitching in the sky...
![Mod Pic 003](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/c2726b74-2a20-4920-af90-25de5ae02961)

I tried to debug it myself. I first disabled both "OutsideEnemies.cfg" and "DaytimeEnemies.cfg", leaving only the "Enemies.cfg" active. Then, I re-started the game, landed on the moon and found similar result. 
After that, I changed the value back from "1.410501" to "4.410501", and the mod seemed to be working normal this time. But, the floating twitching bunker spider was still there XD!!! And I presume there's one on every single moon as I've found it everywhere I go, it always spawn on the ship's left side. (Spider from offense.)
![Mod Pic 004](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/33ffed57-1ebb-4cfa-8f24-11b0b386b0f9)

At this point, I think I need some help... Thanks.

Edit: I tried using the original cfg files generated by your mod without changing any value inside. The result is the same:
Under normal circumstances, the list shouldn't be like this, it should only contain the enemies currently on that moon when the ship first landed. Then, as the game progress, newly spawned monsters will be slowly added to the list.
I honestly don't mind that spider as it's funny as hell, but I do hope you can fix the list.
![Mod Pic 005](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/b5a0c1be-897a-4f06-8340-7aca22faf5c4)

Question or Bug No.2:
It's also a little bit weird that your mod prints out a log that's not the adjusted value but the game's default value.
![Mod Pic 006](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/7bfeefb5-f103-4a3d-83dd-48f2568eaa27)
![Mod Pic 008](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/9ea29b53-79b0-4245-be70-19f80bd8e6fd)

**Comment by BananaPuncher714** [comment]
Ah, please ignore the immobile non interactive floating bunker spider and other enemies that may also be in the same situation. The reading given by the ScanForEnemies mod is incorrect. In order to be able to modify the enemy type properties for the 3 different enemy spawns(inside, outside and daytime), I had to create a "fake" enemy for each enemy type. These do not count towards anything in the game and exist purely as a template. I am still trying to look for a workaround that plays nicely with other mods.

That said, the animation curve's value indicates the amount of enemies that can spawn at the given time, if given the chance. Normally it is calculated every 2 hours. If you would like there to be around 1 enemy to spawn every hour, you can use the curve `0:1, 1:1`.

**Comment by FireGeneral** [comment]
> Ah, please ignore the immobile non interactive floating bunker spider and other enemies that may also be in the same situation. The reading given by the ScanForEnemies mod is incorrect. In order to be able to modify the enemy type properties for the 3 different enemy spawns(inside, outside and daytime), I had to create a "fake" enemy for each enemy type. These do not count towards anything in the game and exist purely as a template. I am still trying to look for a workaround that plays nicely with other mods.
> 
> That said, the animation curve's value indicates the amount of enemies that can spawn at the given time, if given the chance. Normally it is calculated every 2 hours. If you would like there to be around 1 enemy to spawn every hour, you can use the curve `0:1, 1:1`.

So... What if I would like to create a peaceful period where players can loot like before 11am or 12pm? How can I achieve that?
I want no inside monsters be able to spawn before 12pm, but outside monsters can still spawn as usual. (Eclipse)

**Comment by BananaPuncher714** [comment]
There are 18 hours a day in vanilla. You can use the animation curve `0:0, .33333:0, 1:5` to prevent spawning before 12pm. As for the log in the console, those were meant to be the default values so that I could use them for debugging.

**Comment by FireGeneral** [comment]
> There are 18 hours a day in vanilla. You can use the animation curve `0:0, .33333:0, 1:5` to prevent spawning before 12pm. As for the log in the console, those were meant to be the default values so that I could use them for debugging.

I see! Thanks again! I really hope you can find a workaround that is compatible with other mods. (That would be perfect!)
