### ISSUE TITLE
Error reported when modifying map scrap, ship unable to land

### ISSUE THREAD

**Issue by TShineCN** [BananaPuncher714/LethalQuantities#30]
**[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: BottleBin (Item)**
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:IL_015A)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LethalQuantities.Patches.RoundManagerPatch.onLoadNewLevelPrefix (RoundManager __instance, SelectableLevel& newLevel) (at <223bad60ee114d889151ca750c087f5b>:IL_04A1)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::LoadNewLevel>(RoundManager,int,SelectableLevel)
StartOfRound+<OpenShipDoors>d__245.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_007F)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by TShineCN** [comment]
It's strange that only some maps have this problem. I tested exp, ass, vow, and march, and only ass and vow have the problem

**Comment by TShineCN** [comment]
Also, I have a question.In 【Configuration.cfg】 When all the settings for [Global] are set to false, and then separate setting a map's scrap , such as set [Level. AssuranceLevel] with ScrapEnable=true.Is the value in 【Scrap.cfg】 set to default if nothing are filled?
![Uploading 111.png…]()

**Comment by TShineCN** [comment]
Also, I have a question.In 【Configuration.cfg】 When all the settings for [Global] are set to false, and then separate setting a map's scrap , such as set [Level. AssuranceLevel] with ScrapEnable=true.Is the value in 【Scrap.cfg】 set to default if nothing are filled?
![Uploading 111.png…]()

**Comment by TShineCN** [comment]
Also, I have a question.In 【Configuration.cfg】 When all the settings for [Global] are set to false, and then separate setting a map's scrap , such as set [Level. AssuranceLevel] with ScrapEnable=true.Is the value in 【Scrap.cfg】 set to default if nothing are filled?
![111](https://github.com/BananaPuncher714/LethalQuantities/assets/54096173/da25b929-63fe-4d2d-a775-dcaeb71c7664)

**Comment by BananaPuncher714** [comment]
Thanks, I'll take a look at this. As for the other value yes. If there is no GLOBAL then it is the same as DEFAULT.

**Comment by BananaPuncher714** [comment]
It seems that those maps have the same scrap listed multiple times as a possible item to use when spawning scrap. I'll have this fixed on the next update.

**Comment by TShineCN** [comment]
> It seems that those maps have the same scrap listed multiple times as a possible item to use when spawning scrap. I'll have this fixed on the next update.

Thank you very much! I really like the mod you made, it is currently the most customizable mod I have ever seen!
