### ISSUE TITLE
Config not generating

### ISSUE THREAD

**Issue by VanilaBOI** [BananaPuncher714/LethalQuantities#31]
I first realized that I only have the Vanilla and Atlas Abyss Folders, and not the E gypt or Starlancer Moons.
Then I thought I thought I will just delete the Folder and have it generate again.
Now it didn't generate any moons, only a empty Configuration file.
I tried to download older versions like 1.1.1 or 1.1.0 or reinstalling it, but only by downloading 1.1.1 I was able to at least generate a Configuration file with something in it only for it to be whipped again by updating it(the moons never generated again).

**Comment by VanilaBOI** [comment]
Also I know I need to start hosting a game for it to generate, I did that every time.

**Comment by VanilaBOI** [comment]
Just figured out that you have to enable the each config there own.

**Comment by VanilaBOI** [comment]
Ne

**Comment by VanilaBOI** [comment]
Nevermind I don't get it. When I make a new client It works after enabling the Moon configs I want but on my main profile with all my mods it wont generate a Configuration file with anything in it. Even if I copy in the Configuration file from the the other profile it just generates a empty enemies.cfg file under the global folder.
Here's my Profile:018d03f9-62af-da7f-0498-f678f3ddb31c

**Comment by VanilaBOI** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalQuantities.Objects.GlobalConfiguration.instantiateEnemyConfigs (LethalQuantities.Objects.GlobalInformation globalInfo, BepInEx.Configuration.ConfigFile fileConfigFile) (at <223bad60ee114d889151ca750c087f5b>:IL_0271)
LethalQuantities.Objects.GlobalConfiguration.instantiateConfigs (LethalQuantities.Objects.GlobalInformation globalInfo) (at <223bad60ee114d889151ca750c087f5b>:IL_001E)
LethalQuantities.Objects.GlobalConfiguration..ctor (LethalQuantities.Objects.GlobalInformation globalInfo) (at <223bad60ee114d889151ca750c087f5b>:IL_0048)
LethalQuantities.Plugin.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <223bad60ee114d889151ca750c087f5b>:IL_007E)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <e27997765c1848b09d8073e5d642717a>:IL_000E)

[Warning: Unity Log] damageTrigger is disabled! Netcode for GameObjects does not support spawning disabled NetworkBehaviours! The InteractTrigger component was skipped during spawn!

**Comment by VanilaBOI** [comment]
Found the Problem.
When I have E Gypt installed it doesn't generate the config.
It's either that or LethalLevelLoader

**Comment by BananaPuncher714** [comment]
Yes, they do something with the EnemyTypes that I need to investigate. They seem to be invalidating some EnemyTypes for some reason.
