### ISSUE TITLE
Global Scrap 

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#36]
Hello sir :) I think i found a bug with global scrap, i enabled global scrap in configuration added zapgun rarity to 100 that's it and i'm stuck on waiting for crew when i launch the ship

Maybe i did something wrong ?

ps:  "per moon" appear to not have this problem

**Comment by BananaPuncher714** [comment]
Are there any errors in the console, and is there any particular moon that this happens on?

**Comment by TheRealMrKam** [comment]
Tested on experimentation and vow, i guess it's all the moons but haven't tried more

Here is what the console says :

[Info   :LethalQuantities] RoundState found, modifying level before loading
[Info   :LethalQuantities] Changing inside enemy values based on the global config
[Info   :LethalQuantities] Changing daytime values based on the global config
[Info   :LethalQuantities] Changing scrap values based on the global config
[Error  : Unity Log] KeyNotFoundException: The given key 'ZapGun (Item)' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:0)
LethalQuantities.Patches.RoundManagerPatch.onLoadNewLevelPrefix (RoundManager __instance, SelectableLevel& newLevel) (at <ba888b1bb37447398972e121e84554d7>:0)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::LoadNewLevel>(RoundManager,int,SelectableLevel)
StartOfRound+<OpenShipDoors>d__245.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

**Comment by BananaPuncher714** [comment]
Ok thanks, I'll take a look at this.

**Comment by TheRealMrKam** [comment]
Other issue, shotgun minvalue and maxvalue have been swapped which block the game on seed if i want it to spawn.

Fixed it by swapping them on the config.

**Comment by BananaPuncher714** [comment]
It seems like the error with the global scrap was an error on my part. I forgot to use a rarity of 0 if the item didn't naturally spawn in the level.

For the shotgun, it seems like the default values set by the game really are just incorrect. I looked into the logic for it, and it seems like shotguns spawned with nutcrackers are hardcoded to be a value between 30 to 90, and the min/max value isn't actually used. I'll add in a fix next update to properly assign the min/max values in the config, even if the game uses the wrong values. This should also prevent user error if they input invalid min/max values.

**Comment by ourique-gus** [comment]
Hey! Just to point out
I'm having the same issue

Looks like "every time you try to put a scrap item on a moon that don't have this scrap item naturally, you got this error and the game gets stuck"

Like, it tries to access the object in the dictionary, and since the moon don't have it naturally, it fails to access and get crash

**Comment by ourique-gus** [comment]
Hey @BananaPuncher714 
Just to be sure
It is not possible to add scraps to a moon that don't naturally spawn on it?
Or there is a way to do so?

**Comment by TheRealMrKam** [comment]
@ourique-gus It's possible but the global config is currently not working, but i'm spawning store items with per moon config, i can confirm it works.

But i didn't test every items only store items, what are you tring to spawn?

**Comment by ourique-gus** [comment]
@TheRealMrKam I just tried to add all items with >0 rarity in global
I will try to do it on individual moons
