### ISSUE TITLE
Very slight issue with WastelandMoon

### ISSUE THREAD

**Issue by jeffthepuppet** [BananaPuncher714/LethalQuantities#37]
When ran alongside AdvancedCompany, the audio is completely muted when you first load into a save. Yes, you can chance the audio setting and it resets it appropriately, so this isn't too big of an issue, but I still thought I'd bring attention to it since I noticed it still wasn't patched out. Love this mod and hope I can use it in my modpack without breaking anything. I've also had issues where the config file never generates, instead just giving me a blank file. If I figure out which mod is responsible, I can open another issue here if it helps.

**Comment by BananaPuncher714** [comment]
Are there any errors in the console? I'm not entirely sure why LethalQuantities would affect the audio, seeing as it shouldn't touch anything remotely related to it. The config not generating should definitely print out some sort of error message in the console, too.

**Comment by jeffthepuppet** [comment]
So I'm narrowing it down now, it's one of the moons I have installed that creates a sorta 3-way incompatibility. I'll tell you when I track down which. Oh, and I found that the audio bug and the config bug are linked by this moon. When it's disabled, both seem to work fine. I'll also test if this mod functions when I track it down and turn it off just to make sure everything's okay with AdvancedCompany.

**Comment by jeffthepuppet** [comment]
I was 200% correct, lol. It was a mod called "WastelandMoon", basically a stand-in I have for Orion since it breaks spawn-rates. Not sure if this is work looking into too much, but just wanted to make you aware in case this is something other moons may be susceptible to.

**Comment by BananaPuncher714** [comment]
Thanks, I'll take a look at the moon, but if it is a problem on their part then I can't do anything about it.

**Comment by BananaPuncher714** [comment]
It seems like WastelandMoon uses square brackets for the name of its SelectableLevel object, which can't be saved as a config table name:
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/f24573ba-0ab8-4012-bbc4-81965117c4f0)
Ideally, they'd use basic characters for the name(which is different from the PlanetName), so that I can save the name as-is in the config/file without needing to change anything. I can try to add a fix in, but I'm hesitant since that isn't a clean solution.

**Comment by jeffthepuppet** [comment]
It's also a very unique case that I doubt you'd have to run into problems with again. I say leave it.
