### ISSUE TITLE
No SpawnAmountRange for OutsideEnemies

### ISSUE THREAD

**Issue by Riameime** [BananaPuncher714/LethalQuantities#38]
It seems that General/SpawnAmountRange parameter is not generated in config files (global/local) for OutsideEnemies.
Will it work if I add it manually for now?

**Comment by BananaPuncher714** [comment]
No, it is hardcoded to 3 and not a value that can be changed.

**Comment by Riameime** [comment]
Well, that I did not expect :D 
Good to know thanks!
