### ISSUE TITLE
No configs.

### ISSUE THREAD

**Issue by itsdeadfrosty** [BananaPuncher714/LethalQuantities#4]
have tried starting a game with mod loaded. no config generated. u sure your mod works?

**Comment by BananaPuncher714** [comment]
Yes, you need to host a game and load onto the ship before the configs will generate. This is so the mod can gather the information for all custom levels, items and enemies. I am still looking for a way to do it on startup.

**Comment by Camden-Tech** [comment]
I have also had this issue. Maybe it is not a question of whether the configs generate, but where? I am looking through both the windows explorer and thunder store's config tab and i cant find the generated configs. Maybe give a video tutorial or a walkthrough on how to access the configs and to tell whether they generated in the main page.

**Comment by BananaPuncher714** [comment]
They should be generated in thunderstore/r2modman's config editor section like so:
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/2dd17d79-ba40-4ffd-b1db-2cbc9edc6a1a)
What mods are you using? There may be some unknown incompatibility.

**Comment by Camden-Tech** [comment]
Well, lets try to narrow down what the incompatibility is first before I start searching my 64 mods list (most are QoL but whatever).
I see your mod has a loading message in prompt, but I dont see a "loaded" message in the prompt. Is there a loaded message? that could inform us whether the mod got through the initialization stage or not.

**Comment by Camden-Tech** [comment]
[Info   :   BepInEx] Loading [LethalQuantities 1.0.6] but no [Info   :   BepInEx] Plugin loaded [LethalQuantities 1.0.6]

**Comment by BananaPuncher714** [comment]
It seems like an error on my end. I'll narrow down the issue and upload when I can confirm it is fixed. Thanks for your bug reports!

**Comment by itsdeadfrosty** [comment]
Yeah I loaded into a game and they’re still not thereOn Dec 18, 2023, at 13:57, BananaPuncher714 ***@***.***> wrote:﻿
Yes, you need to host a game and load onto the ship before the configs will generate. This is so the mod can gather the information for all custom levels, items and enemies. I am still looking for a way to do it on startup.

**Comment by itsdeadfrosty** [comment]
Ah okOn Dec 18, 2023, at 16:01, BananaPuncher714 ***@***.***> wrote:﻿
It seems like an error on my end. I'll narrow down the issue and upload when I can confirm it is fixed. Thanks for your bug reports!

**Comment by BananaPuncher714** [comment]
Did you update to version 1.0.7?
