### ISSUE TITLE
Every item is generated max value if using local config

### ISSUE THREAD

**Issue by Riameime** [BananaPuncher714/LethalQuantities#42]
I see it was reported in #41, just want to provide additional info in case you need it.

Testing with LQ+Detailed Scan only.

018d3528-5063-367f-28f2-f6aa4846f29f - only global configs enabled, everyting is fine, scrap is generated with different values.

018d3530-487b-1f69-5982-b7eb1b2c693b - enabled local configs and disabled globals, no other changes (same with globals on) - every item is generated with max value e.g. V-Type Engine = 140 * 0.4 = 56.

018d3539-a5ff-0dd7-ce71-94d495f79363 - final test. I change 
global values of V-Type engine 
and local values of Large Axle on Experimentation 
to 500/1000.
Both items generated 1000 * 0.4 values.

My guess is mod reads min scrap values from MaxValue in local config since it happens both if specified and through inheritance.

**Comment by Riameime** [comment]
BTW is there any chance you are planning to add configurable moon route prices? Cause it's probably the only thing missing from otherwise perfect mod (big fan of dungeon and traps config!)

**Comment by BananaPuncher714** [comment]
During last patch, in order to prevent the min from being max, I accidentally set the min to the max value. It should be the same as issue #41. I'll look into configurable moon route prices, but it may not be possible due to how a lot of other mods handle it.
