### ISSUE TITLE
Suspected error?

### ISSUE THREAD

**Issue by ByblackSun** [BananaPuncher714/LethalQuantities#43]
I installed a new version of the mod and started a new record. After launching the ship, I quit the game and reopened it. The cutoff amount becomes abnormal I installed Dynamic Comapny+DynamicDeadline+ExtraDaysToDeadline

normal circumstances
![20240124190308_1](https://github.com/BananaPuncher714/LethalQuantities/assets/155830927/2694e763-9be8-41bf-bb82-cc1d8713dcc4)

abnormal
![20240124190254_1](https://github.com/BananaPuncher714/LethalQuantities/assets/155830927/2477ad09-9074-45c4-a002-b94e10ba1383)

**Comment by jeffthepuppet** [comment]
This is usually an issue I encounter when using GameMaster with my own mods. If you have that, try turning it off and using something like ChatCommands instead.

Alternatively, leave the lobby immediately after loading in and start another save. This will load a game that doesn't have this error, though you'll have to do it each time you load into the game.

**Comment by BananaPuncher714** [comment]
Can you provide a profile code with the suspected bug? LethalQuantities doesn't change the quota or the length of the days, and by default all options are disabled, so it shouldn't affect the base game in any way. What config options have you changed?

**Comment by NekumaBoy** [comment]
I am having the same issue here, what i changed was scrap so that a certain scrap had a rarity of 100000 and modified the enemy config files so that power was higher and some would spawn more frequently.

**Comment by ByblackSun** [comment]
> 您能否提供疑似錯誤的設定檔代碼？LethalQuantities 不會更改配額或天數長度，並且預設所有選項都已停用，因此它不會以任何方式影響基礎遊戲。您更改了哪些配置選項？

I don't know. I only adjust the number of enemies.

**Comment by BananaPuncher714** [comment]
There was an error when loading into the game, that would cause LethalQuantities to fail loading, which for some reason affected other mods. It should be fixed next update:
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/9cfcdf4d-a4ae-4ab5-b19e-78f546d3e71f)
