### ISSUE TITLE
A compatibility bug & suggestion

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#45]
Bug - Modded Moons
I've recently tried this mod and altered the configs for moon prices, but whenever I do navigation seems to stop working. I'm frozen waiting for the ship to move from point A to point B, and if I try to quit it just freezes up. This occurred on both Auralis, from Starlancer Moons mod, and Infernis, from the Infernis mod. Quitting also completely corrupts the file for me, removing all my suits, cuasing TooManySuits, to start spamming errors and the CorporateRestructure mod to break. Even deleting the file and starting a new one won't fix it. This is the screenshot I got of it happening, but not sure what it means beyond what config is causing the issue.
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/cd911755-78ab-4b6f-84d5-4f6e7fc7a0a5)

Also, there's a feature I'd like to request. The LCLightsStartOffMod mod causes all lights to be turned off, which is nice for some moons, but I can't pick or choose which ones this works on. Could you add something like this, but more configurable, to LethalQualities?

**Comment by VioletXe** [comment]
Nothing super difficult, I think? A config allowing specific moons or interiors, like MoreInteriors, to have lights off by default. If it's too out of your way that's cool, I can try with them. I just thought I might get a more customizable or mod compatible result with your work. Plus my profile getting to 110+ by this point which makes disabling, sorting, and uninstalling mods rough on low end computers. It's not a serious problem though.

**Comment by BananaPuncher714** [comment]
I would prefer if you ask them first, in part since it's what their mod is specifically designed for, and seems a little out of place for this mod, but I will look into it in the future if it's something that I can incorporate in a nice way.
