### ISSUE TITLE
Outside & daytime enemy configs don't seem to get respected 

### ISSUE THREAD

**Issue by MommaAnarchy** [BananaPuncher714/LethalQuantities#47]
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/158394555/beb79135-7f0c-498d-9830-2c8f642c5b2b)
 Everything seems to work fine with inside enemies and their spawn rarities and such, but outside enemies don't seem to spawn properly regardless of what you set them to. 
 
 Here's a basic pack I just made for testing with the values I'm using in my own mod pack. I'm just going to Experimentation should be having Baboon Hawks & Hoarding Bugs spawn outside at 75 & 56 rarity respectively, but only Eyeless dogs & earth leviathans are spawning in my game. 018d6272-dc6b-4dde-75cd-4b80125a6dd5
 
 As well, here are BepInEx logs & actual game logs 
[LogOutput.log](https://github.com/BananaPuncher714/LethalQuantities/files/14119456/LogOutput.log)
[Player.log](https://github.com/BananaPuncher714/LethalQuantities/files/14119459/Player.log)

Thank you for any help in advance!

**Comment by BananaPuncher714** [comment]
Ok thanks, I'll take a look at this when I get the time.
