### ISSUE TITLE
Shotgunless Nutcracker

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#48]
I think this may be another case of scrap not generating properly. For some reason Nutcrackers spawn without their shotguns resulting in this spammed error. While they still act like they've got a shotgun by occasionally shooting, accompanied by the ringing tinnitus SFX, but it deals 0 damage and they'll almost exclusively begin kicking.
![Screenshot 2024-01-31 230132](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/5283f1bd-d6c3-47ef-8193-8e91fff42152)
I thought it might've been another mod, but upon testing the removal of LethalQuantities on Auralis, Nutcrackers worked just fine. This seems to only apply to modded moons as it works fine on vanilla moons? Rend & Dine didn't seem to have this issue. Unfortunately, due to the way I'm playing I can't verify whether or not it's the scrap or enemy config that causes this issue.

**Comment by BananaPuncher714** [comment]
Hmm I'll do some testing on this. I haven't actually seen the nutcracker, but I'm not sure why this would be the case.

**Comment by jeffthepuppet** [comment]
Ran into this same issue, the shotgun still exists in the map and animates, but isn't able to leave its origin and just doesn't follow the nutcracker.

**Comment by BananaPuncher714** [comment]
Can you provide a profile code for this? I've tested Auralis with only nutcracker spawns, and I have not been able to find any nutcrackers without a shotgun.

**Comment by jeffthepuppet** [comment]
Hey, can't do any testing right now and I know this is late, but I think it might be spawning them outside that breaks them. I got the same exact error as the post creator.

**Comment by BananaPuncher714** [comment]
Ok, I'll take a look sometime and try spawning them outside on vanilla/custom moons. Whether or not it's outside or inside shouldn't really matter though, but I could be mistaken. Any more information would be helpful.

**Comment by VioletXe** [comment]
Sorry for going dark, after the modded scraps became fixed I had to quickly get everything working for someone's stream so I hadn't the time to respond, but I should be able to send a code shortly if I can still replicate it. Don't know if anything's changed since the newest LQ update.

**Comment by VioletXe** [comment]
Nutcracker shotgun issue seems to have been resolved in the newest patch, but still dunno what was causing it.
