### ISSUE TITLE
Issue with Lategame Upgrades contracts

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#49]
Hello, i found an issue with the mod lategame upgrades, when i launch a contract on a moon i'm having no monsters spawns(lategame upgrades modder told me they are supposed to spawn like usual) when lethal quantities is on, while my  lethal quantities is setup to spawn a lot of monsters without it they do spawn but vanilla rate

**Comment by BananaPuncher714** [comment]
Can you provide a profile code for this, and steps to recreate? I've tried to do some testing, but I can't seem to get no enemies to spawn.

**Comment by TheRealMrKam** [comment]
Humm wierd i just create a new game take a contract for experimentation go there and nothing spawns exept scrap and the lategame contract items... is it possible that 2 mods together make it no spawn  ?
...i'll do more testing.
What's a profile code ?

**Comment by BananaPuncher714** [comment]
It may be, but I have no clue. I don't know why the contracts would really be interfering with any enemy spawns, since LethalQuantities tries to use vanilla variables as much as possible.

If you're using R2Modman, you can export your current profile(collection of mods and configs) as a single code, so that other people can download and use it easily:
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/f77c2476-a803-4abc-9897-e66fb6523608)

**Comment by TheRealMrKam** [comment]
Sorry i'm dumb i forgot i didn't update the mod because i didn't want to fuck up the balance in my modlist that was kinda working well ( was still using 1.1.4 of your mod), updating fixed my problem...but with the new update i just noticed that a sandworm spawned on daytime while i have no rarity setup on it, unless you changed where the rarity is set ?

I don't use a mod manager is there any way to get that code without it ?

**Comment by BananaPuncher714** [comment]
If you can list out the mods, and provide the configuration files you're using for both LethalQuantities and LateGameUpgrades, then I can do some testing with that. I haven't moved the rarity setting since 1.1.0, so I'm not sure why it's spawning there. If you disable all the configs in the Global/Configuration.cfg, do any of the errors still exist?

**Comment by TheRealMrKam** [comment]
the lategame upgrades problem  seems to be fixed with the update.
But now i have all of those others. 
All the globals are already disabled, not sure it's due to quantities tho so i'll try without any mods

**Comment by TheRealMrKam** [comment]
[ExperimentationLevel.zip](https://github.com/BananaPuncher714/LethalQuantities/files/14146864/ExperimentationLevel.zip)

**Comment by BananaPuncher714** [comment]
If you disable Enemies, DaytimeEnemies and OutsideEnemies configuration files for Experimentation as well, or disable LethalQuantities completely, do the problems still exist? (particularly the turrets). If no trap configs are enabled, LethalQuantities does not touch the traps in the slightest, so it may be another mod which is modifying it. The max enemy count not being respected may be another mod that might change it too.

**Comment by TheRealMrKam** [comment]
I tested it alone the last time and there still was the problem, i'll now test with disabling the files you said in experimentation.
That's the thing trap config is disabled but still adds things it seems.

**Comment by BananaPuncher714** [comment]
The traps seem to increase each time you visit the moon, even with the configs off. I will do some more testing and see if multiple dogs or worms can spawn, and in daytime. Note that they daytime and outside enemy configs are different configs, but both spawn enemies outside, so if the maximum amount of enemies in both DaytimeEnemies and OutsideEnemies is 1, then it can spawn 2 in total.

**Comment by TheRealMrKam** [comment]
For the traps it happened twice in a raw before now it's not happening but it was a drastic difference, i never saw that much traps if it happens again i'll send a screen.
On daytime i have the dog on 1 but on my outside i have the vanilla value for everything (i didn't change it), the thing is this happen on day start, also i don't have the sandword on daytime and he spawns on daystart also

**Comment by BananaPuncher714** [comment]
Ok, can you provide the list of mods so I can re-create this issue?

**Comment by TheRealMrKam** [comment]
Only Lethal Quantities and FreeCammer right now

**Comment by TheRealMrKam** [comment]
Do you want my full lethal quantities config too ?

**Comment by BananaPuncher714** [comment]
Yes, that would be helpful, thanks

**Comment by TheRealMrKam** [comment]
[LethalQuantities.zip](https://github.com/BananaPuncher714/LethalQuantities/files/14149455/LethalQuantities.zip)

**Comment by BananaPuncher714** [comment]
It seems like I had not completely fixed the daytime and outside enemy mixup, so daytime enemies was getting replaced with outside enemies, which would explain why sandworms were spawning. This will be fixed on the next update

**Comment by TheRealMrKam** [comment]
Nice ! Thank you :)
