### ISSUE TITLE
Not an issue, but is this host only?

### ISSUE THREAD

**Issue by spinmastercodes** [BananaPuncher714/LethalQuantities#51]
im trying to balance some stuff so me and my bro can get to  high quotas with only 2 players. he cant download mods so im wondering if only the host needs this mod.

**Comment by BananaPuncher714** [comment]
Yes, only the host should need this mod. I haven't tested it with prices or dungeon generation though, so those may be slightly different.

**Comment by spinmastercodes** [comment]
thank you!
