### ISSUE TITLE
 No spawn problem on day 3 and 4

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#52]
After more testing i'm re-opening an issue for the no spawn problem on day 3 and 4 (and maybe after too, didn't try that far) to confirm it comes from lethal quantities.

Here is what i tested:

1. Lethal quantities (with freecamer to check): 

   - experimation day 1,2,3,4 = No monster spawn on day 3 and 4.
   - march day 1,2,3,4 = No monster spawn on day 3 and 4.
   - experimation day 1, offense  day 2, vow day 3, assurance day 4 = No monster spawn on day 3 and 4.
                                                                  
2. Vanilla (with freecamer to check): 
    - experimation day 1,2,3,4 = takes time but monsters spawned even on day 3 and 4 eventually.

The no spawn is until the end (force departure) and is not dependant of the planet.

Here is my lethal quantities config ( it's still the same as the last post).
[LethalQuantities.zip](https://github.com/BananaPuncher714/LethalQuantities/files/14154482/LethalQuantities.zip)

**Comment by BananaPuncher714** [comment]
Ok thanks. I'll do some testing on this and get back to you.

**Comment by TheRealMrKam** [comment]
Oh i see wierd thing, so it's because i set it to 0
Can you explain to me what SpawnAmountRange does exactly ? 
Because how i understood it is, it change the values in the SpawnAmountCurve by a randon number between 3 and -3 if you use 3 which makes the spawns super random and difficult to control am i right ?

**Comment by BananaPuncher714** [comment]
Yes, that's correct. Unfortunately, this is the best that can be done with the base game spawning algorithm.

**Comment by TheRealMrKam** [comment]
Well can't help it then, Thank you ! i'll set it to 1 :)
