### ISSUE TITLE
Code Inheritance/Orphaned config options

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#54]
Just earlier today I deleted a moon I was testing trap spawns on, Infernis.  Everything was going fine for most of the game until we reached Assurance where, amazingly, 35+ turrets were waiting for us. Looking at the configs I can only assume that this issue was caused by traces of configs left behind after I removed Infernis, which was at the top of LethalQuantities configs, jumping over into Assurance, the nearest viable moon in the list. I can probably rectify this issue with a quick redownload of quantities, but I felt it worth bringing to your attention. Here's the code and a picture of the map.
018d7307-74db-ee4e-14d2-f64a07ac9efb
![20240203143458_1](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/0240483e-f3ca-4f31-8cf3-2fe1238ab60f)

**Comment by VioletXe** [comment]
Another picture for what's currently in my configs. This empty area shows up every time I delete something that was installed which I presume to be one of the key aspects of this problem.
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/157070685/79bb55b5-bcc0-4dac-ba8d-f205e0844cc8)

**Comment by VioletXe** [comment]
As expected it seemed to resolve itself when reinstalling Infernis.

**Comment by BananaPuncher714** [comment]
Yes, removing mods will leave empty sections in the global/enemy/scrap/etc configs, but I was not aware that it would carry over like that. I'll look into it and see what I can do, but no guarantee since this is a BepInEx config api issue.

**Comment by VioletXe** [comment]
No worries that's cool. I just thought I'd bring it to your attention since it might crop up again, even if you can't fix it. It made for a hilarious mental breakdown at the terminal during our gaming session and it all worked out in the end lol.

**Comment by BananaPuncher714** [comment]
I can remove any orphan options, but it means that if you want to add the mod back in later, you'd have to redo all the settings from scratch. I'd rather not do that though, so I'll leave this issue open until a better solution comes along.

**Comment by BananaPuncher714** [comment]
I've added a new [web UI](https://bananapuncher714.github.io/LethalQuantities/) for editing files, it should eliminate any need for unused or dangling settings. Please let me know if there are any issues with it, thanks!
