### ISSUE TITLE
Not loading dungeon interiors for any modded maps

### ISSUE THREAD

**Issue by kwindischman** [BananaPuncher714/LethalQuantities#58]
Currently, when I try to navigate to a modded moon the logger prints an error "Did not find local config for ${level.name}({level.PlanetName}). Did the configuration files generate properly?" and the interior that I have set for the map doesn't load.

Inside of LethalQuantities/Global/Configuration.cfg I have DungeonGenerationEnabled set to true for each map individually. Everything else in the .cfg is false. I have weights set to each planet's DungeonGeneration.cfg and everything else is default.

I deleted the mod, cleared the configuration folders, and reinstalled to remake the config files from scratch and still got the error on every modded map.

This is the first issue I have posted before so lmk if you need any more info. It works as intended on vanilla maps.

**Comment by BananaPuncher714** [comment]
Thanks, this is an issue with LethalLevelLoader changing the object names of custom moons which made it not possible for LethalQuantities to identify the moons based on name. This will be fixed next update.
