### ISSUE TITLE
Incompatibility with Brutal company minus

### ISSUE THREAD

**Issue by TheRealMrKam** [BananaPuncher714/LethalQuantities#59]
Hello, i just installed BCM and found out that the scrap settings i set in LQ don't work with it, dunno if its due to LQ or BCM... just letting you know :)

Edit: BCM seem to also have a problem with Advanced Company scrap so it seem it comes from BCM i guess.

**Comment by BananaPuncher714** [comment]
Thanks. When you say does not work, do you mean that there is an error in the console, or that BCM overrides whatever values you set in LQ? If BCM overrides LQ values, then there is nothing I can do about that.

**Comment by TheRealMrKam** [comment]
I think BCM overrides LQ's values yes, haven't seen any error in the log :/

**Comment by TheRealMrKam** [comment]
This has been fixed !
