### ISSUE TITLE
Stuck on map loading screen when using generated Presets.json

### ISSUE THREAD

**Issue by Forgy95** [BananaPuncher714/LethalQuantities#65]
Hello, so I am not sure if I am just really stupid or it just isn't working. When I generate config (Presets.json) with web UI and replace it in my profile, result is a few errors in log and I am not able to land on moon anymore. I tried multiple variants but even if I use new profile with only BepInExPack and LethalQuantities in it, and generate raw .json from web without changing anything, it doesn't work. I can only land on moon if I don't touch original .json file. 
[LogOutput.log](https://github.com/BananaPuncher714/LethalQuantities/files/14409523/LogOutput.log)

**Comment by BananaPuncher714** [comment]
Ok, I think I know what might be causing this error. Can you try with this preset?
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14409857/Presets.json)
It seems like I didn't account for the case where no options were selected

**Comment by Forgy95** [comment]
Yes, with this one it is working. This problem also occured with this preset where I changed/added only enemies spawn weights on all maps and scrap amount (+dungeon size) on one.
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14409949/Presets.json)

**Comment by BananaPuncher714** [comment]
Alright. This will be fixed next update. Thanks!

**Comment by Forgy95** [comment]
Great, thank you very much! Really like these mod possibilities, looking forward to using it 👍
