### ISSUE TITLE
A possible discord for better communication

### ISSUE THREAD

**Issue by MegaRaptor123** [BananaPuncher714/LethalQuantities#66]
Either a standalone server, or a thread on the modding discord. Great for questions and for new people to discover the mod

**Comment by BananaPuncher714** [comment]
I'll have to think about it. I currently cannot join the Lethal Company modding discord or any new servers because I am in too many servers/don't have nitro, but if the opportunity arises, I will.

**Comment by BananaPuncher714** [comment]
There is a discord thread for this mod intended for general communication in the lethal company modding discord under the mod-releases.
