### ISSUE TITLE
just not working

### ISSUE THREAD

**Issue by FoxivanFable** [BananaPuncher714/LethalQuantities#67]
at some point the mod just stopped working, neither the web ui or the manual config files work

**Comment by BananaPuncher714** [comment]
Are there any errors in the console? Can you provide your Presets.json file, as well as the LogOutput.log?

**Comment by FoxivanFable** [comment]
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14413271/Presets.json)

gonna relaunch the game to check for errors as well as get the log

**Comment by FoxivanFable** [comment]
[LogOutput.log](https://github.com/BananaPuncher714/LethalQuantities/files/14413300/LogOutput.log)

couldnt check for errors since LC_Office keeps saying that shrimp is false or something, and it keeps putting my down to the start of the console

**Comment by BananaPuncher714** [comment]
Is the problem that the prices are not being set properly? I forgot to provide default preset values for levels that don't have any prior configuration, which would have made the prices not update unless you went to specific moons with a valid preset.

Can you try with this preset and tell me if it works?
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14413402/Presets.json)
I loaded your generated preset into the web ui, then downloaded it again.

**Comment by FoxivanFable** [comment]
hasnt seemed to work, would going to the moon possibly change it? yes i am trying to change the moon prices

**Comment by BananaPuncher714** [comment]
Yes, the issue with the current version of LethalQuantities is that if you do not modify any configs for a moon, then a preset for that moon is not generated, even if a global option was specified. That preset I gave you should have had a preset for each moon, but I forgot to change the parent to the exported global, instead of the local global. Can you try with this updated file:
[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14413531/Presets.json)

**Comment by FoxivanFable** [comment]
routed to secret lab on a different save file and now its fixed for all saves thanks a bunch, hope to see this get fixed as this mod is really useful for people who want to personalize their game as much as i do

**Comment by BananaPuncher714** [comment]
Thanks for confirming, I'll post an update soon(ish) which should fix this issue.
