### ISSUE TITLE
Unable to Land on Any Moon

### ISSUE THREAD

**Issue by TheDebbyCase** [BananaPuncher714/LethalQuantities#68]
I've actually managed to narrow down the issue quite nicely. It seems Zeekers has his own moon for debugging enemies called "TestAllEnemies", which seems to be breaking your config loading sequence. I'm unsure why I'm having this problem and others aren't, but regardless, it does seem to be the issue. Here is the preset I am currently using:

[Presets.json](https://github.com/BananaPuncher714/LethalQuantities/files/14427038/Presets.json)

I am heavily modded, and the issue doesn't seem to occur in vanilla with only LethalQuantities, but I fail to see, from reading the log, how any of the mods I have could be causing the issue. The main error occurs at line 3174, where usually it would be expected to say:

> [Warning:LethalQuantities] Unable to find price of TestAllEnemies()

It instead gives:

> [Error  :LethalQuantities] Encountered an error while trying to load the configuration

Followed by:

> [Error  :LethalQuantities] Please report this error to the mod developers: System.InvalidOperationException: Sequence contains no matching element
> at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_0011
>at LethalQuantities.Patches.RoundManagerPatch.onStartPrefix (RoundManager __instance) [0x00149] in <bb2c9c826506470b8df1b4881c0c8f3f>:IL_0149

[LogOutput.log](https://github.com/BananaPuncher714/LethalQuantities/files/14427148/LogOutput.log)

The issue is not LethalLevelLoader, the error occurs even without it. Following the error I mentioned, it seems LQ is unable to continue reading the config files and so never finds the dungeon flows, and therefore cannot load into any moon. You'll see two instances of an error beginning with:

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

starting at line 4139. Hopefully, if this is somehow something I got wrong in my Presets.json, you can let me know. Or if there's any known conflicts at all, I have my modslist here too:

[Modslist.txt](https://github.com/BananaPuncher714/LethalQuantities/files/14427195/Modslist.txt)

Thank you in advance, and thank you for the mod <3

**Comment by TheDebbyCase** [comment]
I should add, I **shouldn't** have any other mods affecting the moons and their settings in any way, but there's always a possibility I am dumb and forgot

**Comment by BananaPuncher714** [comment]
Thanks, I'll have this fixed next update

**Comment by TheDebbyCase** [comment]
> Thanks, I'll have this fixed next update

Ah I suppose you already know where to look? Good luck!
