### ISSUE TITLE
Compatibility and Floating Enemies when using v1.0.7

### ISSUE THREAD

**Issue by FireGeneral** [BananaPuncher714/LethalQuantities#7]
Hello! Sorry to bother you again, but I notice both "compatibility with other mods like ScanForEnemies" and "randomly floating enemies" that were supposedly fixed in v1.0.6 came back in v1.0.7
![Mod Pic 010](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/914f48ea-ebd6-42a4-bea1-06d645a6e45a)
![Mod Pic 011](https://github.com/BananaPuncher714/LethalQuantities/assets/82710934/9c975192-bfc9-44ed-9869-50ebdc118a58)
Both pictures were taken using v1.0.7

Edit: I checked v1.0.6, and it turned out that the reason both previously mentioned things were fixed was because the mod's config files weren't getting saved/loaded. (Just like you said in your Changelog)
So... when you fixed it so that it could save/load the config files again, those things also came back since they weren't actually fixed :(
Btw, there's a mod called "PestControl" which could adjust enemy spawn weights without the need of spawning fake enemies.
Sorry if that doesn't help as I don't really understand the mechanics, but I really like your mod since it provides a lot more options than the others, and it personalizes and enhances me and my friends' experience a lot :)

Again, thank you for your hard work!

**Comment by BananaPuncher714** [comment]
Yes, I did unfortunately mess up on the 1.0.6 release and prevent any configs from being loaded, which meant nothing spawned, but nothing worked. I'm currently trying to fix this issue and will update as soon as I can. Thanks!

**Comment by FireGeneral** [comment]
> Yes, I did unfortunately mess up on the 1.0.6 release and prevent any configs from being loaded, which meant nothing spawned, but nothing worked. I'm currently trying to fix this issue and will update as soon as I can. Thanks!

No worries, please take your time! Thank you for bringing this mod to the community!

**Comment by BananaPuncher714** [comment]
I tested v1.0.8 with ScanForEnemies as well, and it seems to have worked. However, ScanForEnemies does not always update correctly, especially if some enemies are not naturally spawned into the game. The spider issue still remains, which I am still investigating.
