### ISSUE TITLE
Potential spawnrate mixup?

### ISSUE THREAD

**Issue by VioletXe** [BananaPuncher714/LethalQuantities#70]
I'm unsure if this is an inheritance issue since I haven't yet recreated the pack... still a bit burnt from remaking everything the last time, but my current pack seems to be confusing the Bracken spawn weights with the Masked? On Experi the bracken weight is 14 which gets applied to Masked which also seems to occur on Triskelion. That's about the extent of my testing so far and this is the profile code.

018dedcd-9162-0395-1f13-9c03f58fe5ea

And while I'm making this post  I wanted to broach a question as well. Is the preset I create able to be shared via thunderstore codes? Every time I edit profiles the changes aren't transferred. Are LQ's presets able to circumvent that issue with presets being considered "part of the mod" and therefor sharable through codes or no?

**Comment by BananaPuncher714** [comment]
In your MaskedEnemyOverhaul/MaskedEnemyRework config, there are two settings which need to be set in order for other mods to properly set the masked's rarity.
![image](https://github.com/BananaPuncher714/LethalQuantities/assets/17506677/e2b8050b-83c5-4152-84c0-86a675e9d495)
While the `Use Spawn Rarity` is false, the `Use Vanilla Spawns` is also false, resulting in masked enemies having the same rarity as the bracken.

Yes, thunderstore codes that you share will include anything in the config folder, so the `Preset.json` file which you are using will also be included. I'm not sure if you're have issues with it or not, but it is essentially treated as any other config file. If it's something to do with the web UI not applying, then the only things I can think of is, either you aren't downloading the modified preset, or you saved it to the wrong location.

**Comment by VioletXe** [comment]
Weird, this must've been an Issue I've had for awhile because I only recently noticed my masks were broken all together so I guess this just sort of snuck up on me. Also that's a relief, thanks for clearing up the code thing for me. This mod's at the heart of my modpack and I love it to death, so anything that could go wrong with this terrifies me more than anything in game. Thanks again ^.^/

**Comment by BananaPuncher714** [comment]
Closing, but feel free to reopen if you encounter a similar issue again.
