### ISSUE TITLE
spawn chance curve seems too random

### ISSUE THREAD

**Issue by TShineCN** [BananaPuncher714/LethalQuantities#74]
In previous versions (1.0-1.1), I used 【spawn chance curve】 to change the speed of monster spawn. For example, when I want to spawn four 【Forest Keepers】 as soon as the ship lands on Vow, I set the first node of the 【Outside enemy spawn chance curve】 to (0,4)(1,4). Then set the node of the 【spawn chance curve】 for Forest keepers to (0,4)(1,4)or(0,100)(1,100). This will take effect in the game.At the same time, other monsters outside that have not been set can spawn according to the original curve. But after version 1.2, I set it up like this again. Although can spawn monsters just after landing, the monsters are of different types and the number is not equal to 4. No matter how I set the 【Outside enemy spawn chance curve】 and 【spawn chance curve】 for each monster, I cannot solve this problem. The spawn monster becomes very random.

**Comment by TShineCN** [comment]
![111](https://github.com/BananaPuncher714/LethalQuantities/assets/54096173/a603a7f0-0fd2-46e0-8203-7c2a4881fa9f)
This is the relevant image

**Comment by BananaPuncher714** [comment]
Can you provide your Presets.json file? It is not possible to set the exact amount of outside enemies spawned, unlike daytime enemies, which have a spawn amount range.

**Comment by TShineCN** [comment]
This is my JSON file. And the cfg files of older mod versions.
I made Vow's outside can spawn Brackens. When the ship just landed on Vow, four Brackens were spawned. If I want the to spawn other monsters as soon as ship lands, I can also set it as long as the parameters are the same as Brackens. But it cannot be implemented in the latest mod version. When I still set this parameter, only Brackens should spawn when the ship just lands. Now all external monsters in the list have a chance to spawn when the ship just lands.
[Presets (1).json](https://github.com/BananaPuncher714/LethalQuantities/files/14448631/Presets.1.json)
[OutsideEnemies.zip](https://github.com/BananaPuncher714/LethalQuantities/files/14448637/OutsideEnemies.zip)


> Can you provide your Presets.json file? It is not possible to set the exact amount of outside enemies spawned, unlike daytime enemies, which have a spawn amount range.

**Comment by BananaPuncher714** [comment]
Ok, I will take a look at this and do some testing, then get back to you.

**Comment by BananaPuncher714** [comment]
It seems like I did not set the max enemy count properly, so even though you set there to be 4 brackens, it would only spawn 1. I'll have this fixed next update.

**Comment by TShineCN** [comment]
> 似乎我没有正确设置最大敌人数量，所以即使你在那里设置了 4 个蕨菜，它也只会生成 1 个。下次更新时，我将修复此问题。

I understand, thank you very much!!
