### ISSUE TITLE
Walker enemy from diversity does not appear in the enemy list 

### ISSUE THREAD

**Issue by GoofyVlad** [BananaPuncher714/LethalQuantities#75]
The walker enemy from diversity does not appear in the enemy list i cant add him to custom moons

**Comment by GoofyVlad** [comment]
it shows something called bracken (walkertype) is that the walker?

**Comment by BananaPuncher714** [comment]
Yes, the first value(name) is taken from the scan node of the enemy prefab, but I guess the scan node for the walker is not correct or something.

**Comment by GoofyVlad** [comment]
ill close this now
