### ISSUE TITLE
Add New Content to Existing Presets.json

### ISSUE THREAD

**Issue by TheDebbyCase** [BananaPuncher714/LethalQuantities#76]
Hi, just wondering if there's any way to add new content to an existing preset, or if I'd need to make a new presets list? For instance, I have made a Presets file for my modpack, and I decided to add a couple of new scrap mods to my modpack. I expected them to be added to the pool of available scraps but they weren't there. AM I doing something wrong, or is there currently no way to achieve this? Thanks

**Comment by TheDebbyCase** [comment]
I now seem to be unable to generate a new Presets.json altogether. I feel like there's something fundamental I'm not getting. Do I need to reinstall LethalQuantities to generate a new Presets.json?

**Comment by TheDebbyCase** [comment]
I reinstalled LethalQuantities and not even the legacy config is being generated, could there be a mod preventing it from loading?

**Comment by TheDebbyCase** [comment]
> [Error  :LethalQuantities] Encountered an error while trying to load the configuration
> [Error  :LethalQuantities] Please report this error to the LethalQuantities mod developers: System.InvalidOperationException: Sequence contains no matching element
> at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_0011 
> at LethalQuantities.Patches.RoundManagerPatch.onStartPrefix (RoundManager __instance) [0x00135] in <76ec033cd3574ee29ec931c68147c6f5>:IL_0135

**Comment by BananaPuncher714** [comment]
Do you have the RouteRandom mod?

**Comment by BananaPuncher714** [comment]
By default, whenever you install or remove a mod, the lists of valid enemies/scrap/traps should be updated automatically. If you can provide a profile code, I can take a look to find the error. Thanks!

**Comment by TheDebbyCase** [comment]
> Do you have the RouteRandom mod?

I do, I will try removing this and seeing if it all works as expected

**Comment by TheDebbyCase** [comment]
> By default, whenever you install or remove a mod, the lists of valid enemies/scrap/traps should be updated automatically. If you can provide a profile code, I can take a look to find the error. Thanks!

I removed RerouteRandom and it all works as expected, thank you

**Comment by BananaPuncher714** [comment]
Ok thanks for confirming, I'll have it fixed next update.

**Comment by KAEOAS** [comment]
help wait I don't have routerandom but have the same problem

**Comment by BananaPuncher714** [comment]
What errors are there in the console?

**Comment by KAEOAS** [comment]
Sorry it was my fault, I had another moon randomizing mod and I just forgot I guess. Sorry to waste your time, I removed it and everything was fine. Have good day oops
