### ISSUE TITLE
not working scrap value

### ISSUE THREAD

**Issue by Mickael46999** [BananaPuncher714/LethalQuantities#8]

**Comment by BananaPuncher714** [comment]
Thanks, I'll investigate this in more detail and hopefully have it fixed next update

**Comment by BananaPuncher714** [comment]
Can you provide more information on what is not working? Have you enabled the config?

**Comment by BananaPuncher714** [comment]
It seemed that the minimum total scrap value and maximum total scrap value variables in the code did not actually change anything. You will now have to set the individual item minimum and maximum values as well as the scrap value multipliers.
