### ISSUE TITLE
Prices not updating

### ISSUE THREAD

**Issue by TheBlueB0mber** [BananaPuncher714/LethalQuantities#80]
Trying to use the WEB UI to adjust moon prices but no changes occur after saving the .json file in the correct location.

**Comment by BananaPuncher714** [comment]
Which preset are you changing the prices in? If you want to modify the prices for each moon overall then you have to change the price in the global preset. Setting prices in the moon preset is per moon. For example, if you change the price of Vow to 100 for the Experimentation preset, Vow will cost 100 credits _only_ when you are on Experimentation.

**Comment by BananaPuncher714** [comment]
Please feel free to reopen if you are still encountering this issue
