### ISSUE TITLE
Where is present.json?

### ISSUE THREAD

**Issue by roboeye789** [BananaPuncher714/LethalQuantities#82]
I understand this is a very small issue but for days I have tried to get the editor up but nothing has been working. The Web Editor keeps asking for _Present.json_ but the only _json_ in the download in _manifest_.

**Comment by BananaPuncher714** [comment]
You need to install the mod, then host or join a game. Afterwards, inside the config directory, the preset file will be present at `LethalQuantities/Advanced/Preset.json`

**Comment by roboeye789** [comment]
Thank you for the reply.
