### ISSUE TITLE
Some items and enemies cannot be added to moons.

### ISSUE THREAD

**Issue by Nemesis041** [BananaPuncher714/LethalQuantities#87]
For reasons I cannot yet identify, there are some enemies and items that I am unable to add to any moon, modded or vanilla, via the web UI.

Current list of items and enemies that cannot be selected in the web UI:

Peepers
Shockwave Drone
Siren Head
Shrimp
Mobile Turret
Cleaning (TZP) Drone
Haunted Harpist
Phantom Piper
Ethereal Enforcer
RedWood Giant

Ganimedes' scrap
Scoopy's Variety scrap (Weezer guitar and fire axe)
All Trophy items (both trophies and medals)
Monster plushies (including the RedWood plushie)

**Comment by BananaPuncher714** [comment]
Thanks, will investigate this further
