### ISSUE TITLE
How tf am i suppose to use this?

### ISSUE THREAD

**Issue by lethalcompanyblahblah** [BananaPuncher714/LethalQuantities#9]

**Comment by Simmmmms** [comment]
Add the mod to your r2modman profile. Start the game then host/join a game. This should generate the configs and you can edit them in the r2modman config editor. The explanations for each config option are in the readme.
[This](https://lethal.miraheze.org/wiki/Mechanics) is a good resource for learning about some of the mechanics.

**Comment by BananaPuncher714** [comment]
If there are any more questions, feel free to reopen this issue.
