### ISSUE TITLE
[Request] Filter for uninstalled

### ISSUE THREAD

**Issue by ProjectBots** [BananaPuncher714/LethalQuantities#92]
Modpacks change over time, causing items/enemies/flows... to no longer exist (or be renamed). However, the corresponding entries in LQ remain and become spam. An option to filter by these entries allows modpack creators to delete these entries and customize related things.

**Comment by BananaPuncher714** [comment]
Are you using the legacy configs, or the web UI? Any options in the web UI should be removed automatically.

**Comment by ProjectBots** [comment]
I saw a dungeon flow i removed still being present in the web ui and assumed it would be same for all entries, but i am unable to reproduce it now. I'm sorry for taking up your time.
