### ISSUE TITLE
March dungeon flow

### ISSUE THREAD

**Issue by MiraakThuri** [BananaPuncher714/LethalQuantities#99]
It seems that it's not possible to change march dungeon flow, i don't know if this a limitation of the original game or from the tool
I suppose it's probably because March use the special 3exit flow of the factory, but i don't mind having a small chance of generating a manor that get 2 of it's 3 fire exit blocked off

**Comment by BananaPuncher714** [comment]
I think this was because of how it was coded initially, but should automatically be fixed in the future versions.

**Comment by MiraakThuri** [comment]
Good to know
thx

**Comment by MiraakThuri** [comment]
This have been fixed by V64 as March now use the regular dungeon flow system (if you use LLL it will also make all 3 fire exits works, if you don't want to have 2 of them being blocked off)

**Comment by BananaPuncher714** [comment]
Ok thanks for the update!
